language: ruby
rvm:
  - 2.3.1
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -h localhost -c 'create database workshops_test;' -U postgres
addons:
  postgresql: '9.5.4'
